### ISSUE TITLE
Scaling with k8s

### ISSUE THREAD

**Issue by jlogelin** [application-research/delta#21]
In order to address PiB scale data ingestion, we should be using best of breed Kubernetes tooling as an optional deployment for Delta.

A general guide to autoscaling a Golang microservice like Delta with Kubernetes:

1. **Containerize Delta as a microservice** 
The first step is to containerize Delta using Docker. This involves creating a Dockerfile that specifies how to build the container image, which includes the Golang code and any dependencies it requires. Once you have created the Dockerfile, you can build the container image and push it to a container registry such as Docker Hub. Delta currently supplies the following `Dockerfile`:
```
FROM golang:1.18 AS builder
RUN apt-get update && \
    apt-get install -y wget jq hwloc ocl-icd-opencl-dev git libhwloc-dev pkg-config make && \
    apt-get install -y cargo
WORKDIR /app/
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo --help
RUN git clone https://github.com/application-research/delta . && \
    RUSTFLAGS="-C target-cpu=native -g" FFI_BUILD_FROM_SOURCE=1 FFI_USE_BLST_PORTABLE=1 make

FROM golang:1.18
RUN apt-get update && \
    apt-get install -y hwloc libhwloc-dev ocl-icd-opencl-dev
```
2. **Create a Kubernetes deployment** 
Next, create a Kubernetes deployment that specifies how to run the containerized Delta microservice. The deployment should include the container image name and any configuration settings such as environment variables and command-line arguments. The deployment also specifies the number of replicas of the microservice that should be running.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: delta-service
        image: my-registry/delta-service:latest
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@database:5432/deltadb"
        ports:
        - containerPort: 8080
```
This YAML file specifies a deployment with three replicas of the containerized Delta microservice. It also specifies an environment variable DATABASE_URL and the container port that the microservice listens on.

3. **Add a Kubernetes horizontal pod autoscaler** 
Once you have a deployment running, you can add a horizontal pod autoscaler (HPA) to automatically scale the number of replicas based on CPU or memory usage. The HPA can be configured to automatically scale up or down the number of replicas based on the average CPU or memory utilization over a specified period of time. To add an HPA, you need to create a YAML file that specifies the scaling behavior and the deployment it applies to.
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: delta-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delta-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
```
4. **Test the autoscaling behavior** 
Once you have set up the HPA, you can test the autoscaling behavior by generating load on the microservice and observing the number of replicas that are created or destroyed. You can use tools such as Apache Bench or JMeter to generate load on the microservice and monitor the CPU and memory usage using Kubernetes dashboard or other monitoring tools.
```
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"sync"
)

func main() {
	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			res, err := http.Get("http://delta-service")
			if err != nil {
				fmt.Println(err)
				return
			}
			defer res.Body.Close()
			_, err = ioutil.ReadAll(res.Body)
			if err != nil {
				fmt.Println(err)
				return
			}
		}()
	}
	wg.Wait()
}
```
